### ISSUE TITLE
Implement code features requested for submission to Journal of Open Source Software

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/physical_validation#37]
https://joss.theoj.org/
https://joss.readthedocs.io/en/latest/submitting.html

**Comment by ptmerz** [comment]
This should probably get some more defined task list or subtasks.

**Comment by ptmerz** [comment]
Here's the part of the review requirements (https://joss.readthedocs.io/en/latest/review_criteria.html) that directly concern the software part:

### Functionality

- [ ] Installation: Does installation proceed as outlined in the documentation?
- [ ] Functionality: Have the functional claims of the software been confirmed?
- [ ] Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is? _(related to #49)_
- [ ] Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution. _(related to #2, #63, #48)_
- [ ] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems). _(related to #49, #50)_
- [ ] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)? _(related to #65)_
- [ ] Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified? _(related to #59, #58)_
- [ ] Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support _(related to #46)_
