### ISSUE TITLE
conda-forge to-do list

### ISSUE THREAD

**Issue by mattwthompson** [shirtsgroup/physical_validation#63]
The PR is open at conda-forge/staged-recipes#11370 but we should do a few things, and make a new release, before anticipating that PR be merged. This issue is to document those things

- [x] General cleanup - largely handled by #41 
- [x] Tests - #59 
- [x] License - #62 ~not~ a blocker ~but if it is going to be changed, it may be easier to have only the new license on forge~
- [x] New release (including new license file packaged)
- [x] Add conda instructions on "Installation" page.
- [x] Update release docs https://github.com/shirtsgroup/physical_validation/wiki
- [x] Update license in conda recipe - we moved to MIT
- [x] Tests have additional dependencies, see `devtools/conda-envs/test_env.yaml`. Do we need to include them in  the conda recipe? Can we reuse that .yaml file to reduce the number of places that list dependencies?

This is all that comes to mind - any other suggestions?

**Comment by SimonBoothroyd** [comment]
Agreed #62 should be resolved prior to pushing to conda-forge

**Comment by mattwthompson** [comment]
This is still blocked by the licensing discussion.

Once that is resolved, this should be a fairly straightforward recipe to re-submit.

**Comment by mattwthompson** [comment]
Looks like #62 is closer to being merged. Once/if that's done, I will need a new version released in order to ensure the new license file is packaged properly (but also useful for the sake of including other changes). Then, I should be able to submit this as a recipe.

**Comment by mattwthompson** [comment]
Now that the licensing issue has been resolved and some progress made on tests, the only blocker is having a release cut. Once that happens I expect to be able to quickly turn around a conda-forge recipe.

**Comment by ptmerz** [comment]
Added a couple of items (test dependencies and license update). Also, I deployed version v1.0.0rc8 yesterday, which I see as the final RC. The one thing missing for the final release is the conda installation. Which yields the question - update the documentation, release 1.0.0, and then get our conda recipe merged? Or get our conda recipe merged, then update the documentation and release 1.0.0, and update our conda recipe with the new version number? The second version is cleaner, of course, but if that poses any problems and the time span between releasing the new docs and having the conda version up is short enough we could probably turn a blind eye...

**Comment by mattwthompson** [comment]
> Do we need to include [test dependencies] in the conda recipe?

No, convention is to only include runtime dependencies.

> Can we reuse that .yaml file to reduce the number of places that list dependencies?

No, there will necessarily be a new `meta.yaml` recipe in the feedstock. I think that amounts to two places that list runtime dependencies, which is more or less unavoidable if we want to distribute it via two package managers (`setup.py` for `pip` and a feedstock for `conda`).

> The one thing missing for the final release is the conda installation. 

In short, I think the release should be made when the source code meets the desired behavior and the packaging dealt with as a downstream consideration. If documentation needs to be updated to reflect packaging changes, I much prefer doing so with a patch release because it avoids a chicken-and-egg problem you just described. Also, conda-forge team is not particularly eager to host RCs and betas, so there needs to be a formal release made to get the process started. Getting it through review can take several weeks to a couple of months because it's run by volunteers, so I want to present as clean and simple a recipe as we can.

If it's a matter of having something installable for reviewers, I can just build them by hand and host them on my channel or a the group's channel. Quick, but not as elegant - recommending `pip` installation would be preferred there.

**Comment by ptmerz** [comment]
Thanks for the insight @mattwthompson. I fully agree with you - let's release 1.0.0 in the current state (pip installation is enough, no need for a temporary conda build). Then we can reactivate the conda PR, and whenever that comes through, we release a patch update including the additional installation instructions.

**Comment by ptmerz** [comment]
Version 1.0.0 has been released, and it contains a LICENSE file with the new MIT license.

**Comment by mattwthompson** [comment]
PR up: https://github.com/conda-forge/staged-recipes/pull/16868

**Comment by mattwthompson** [comment]
We were fortunate to get a quick review and merge from a core member - it should be live within about 2 hours!

**Comment by ptmerz** [comment]
Awesome, thank you @mattwthompson!!

**Comment by ptmerz** [comment]
So I assume that updating to a new version just consists of updating the version string in our repo (unless we're changing fundamental things like dependencies or some of the urls)? Can you give an example of when we would want / need to update the build count but keep the version the same?

**Comment by mattwthompson** [comment]
> So I assume that updating to a new version just consists of updating the version string in our repo (unless we're changing fundamental things like dependencies or some of the urls)?

Basically yes, and there's even a bot that will do it automatically in some cases. Most builds for new versions amount to updating the version/tag, SHA hash, and asking the bot to update everything else. For example, see the two commits in a recent update I did: https://github.com/conda-forge/openff-interchange-feedstock/pull/12

> Can you give an example of when we would want / need to update the build count but keep the version the same?

The [general rule](https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=build%20number) is that the build number should be bumped when something changes in the conda recipe but not the source code. Most commonly this involves pinning or somehow constraining a dependency because something changed or we discovered something wrong. For example, https://github.com/conda-forge/openff-toolkit-feedstock/pull/10 is a recent example in which we made a new build because (for some reason) an old version of an upstream was being pulled down. 
Many other cases it's a matter of fixing errors like forgetting to include a required dependency.

This gets into murky territory pretty quickly since some solvers will at times fall back to a lower build number if it can't solve with the most recent build, so sometimes vanilla installs can misbehave and deliver a "bad" version to a user. This package fortunately has relatively few dependencies so I'm not concerned, but it can be an issue with larger and more complex projects.

**Comment by mattwthompson** [comment]
Anyway, if somebody wants to `conda install physical_validation -c conda-forge` and verify that it's not totally broken, I think we can close this for now and continue any future packaging issues in the feedstock: https://github.com/conda-forge/physical_validation-feedstock

**Comment by ptmerz** [comment]
Yes, this looks good. I will update the docs and wiki instructions and then close this and #2.

**Comment by mattwthompson** [comment]
Perfect - always great to see issues with small numbers being closed

**Comment by ptmerz** [comment]
Alright, closing this! Thanks a lot for your help @mattwthompson!!
